### ISSUE TITLE
CORE-21 - MCD Proxy Contract Implementation

### ISSUE THREAD

**Issue by tomedwardsmith** [makerdao/dss-proxy-actions#1]
Description
We need to implement an MCD Proxy contract, much the SCD interface.

We will require:

OpenProxyCdp
OpenProxyCdpLockAndDraw
LockAndDraw
Wipe (Only in DAI)
Join
Lock
Draw
Wipe
Free
Exit
Transfer – ?? Maybe if it’s possible through Wrapper (@gbalabasquer )

**Comment by tomedwardsmith** [comment]
@gbalabasquer what's the status on this one?

**Comment by gbalabasquer** [comment]
This was done as initial proxy development for `CdpHandler`. I've moved that code to the branch:  `cdp-handler-version`.
Issue #2 is taking care for the newest version for `CdpManager`
